### ISSUE TITLE
Cannot make iOS version work

### ISSUE THREAD

**Issue by alexrainman** [alexrainman/nativescript-carousel-view#1]
Guys, basically this repo is work in progress. I am migrating my CarouselView for Xamarin.Forms to NativeScript.

I got Android version working and ready for release one but i am missing something in iOS. I get this exception:

-[UIPageViewController] Unrecognized selector sent to instance.

I know iOS pretty well but i am not NativeScript expert.

Please take a look at carousel-view.ios.ts file. I have two implementations. One based on my previous plugin for Xamarin and another one that inherits from UIPageViewController and implements DataSource and Delegate in one class.

If we can make this works then i can move forward.

Roadmap:
- Release 1: horizontal scrolling/swiping, TemplateSelectors and methods to Insert/Remove pages.
- Release 2: Vertical scrolling/swiping.
- Release 3: page indicators.

Thanks in advance.

**Comment by alexrainman** [comment]
@bradmartin done https://www.npmjs.com/package/nativescript-carousel-view :)

**Comment by bradmartin** [comment]
@alexrainman Where is the repo for the actual plugin 😄 ? I'm slightly confused. I looked at the package.json after installing the plugin from npm and I believe that's the xamarin repo. So did you publish from this repo in the plugin folder and keep the *package.json* locally off the repo for the plugin? I want to contribute and help but not sure with the current setup.

**Comment by bradmartin** [comment]
K, I see the url clearly now 😄  so it is this repo

**Comment by alexrainman** [comment]
Yes, i just mentioned that its a port of my Xamarin plugin :)

**Comment by bradmartin** [comment]
I think it might be a good idea to move the actual plugin source out of the demo app, so it's easier for contributors to find. I say this because most plugins have followed a good structure from the beginning making it easier for NS devs to figure out. Any of mine or @NathanWalker repo's are setup with this approach, I used his seed project for most of my plugins so it was simple to get setup. No worries if you don't wanna go through the hassle, totally understand 👍 this is great regardless. Very nice work and about to use it in a project.

**Comment by NathanWalker** [comment]
@alexrainman this is fantastic, can't wait to use this in an app soon!

**Comment by alexrainman** [comment]
Thanks guys!

**Comment by alexrainman** [comment]
@bradmartin @NathanWalker @hshristov @tzraikov @NickIliev take a look on how much the plugin has evolved since i started working on it  👍

**Comment by bradmartin** [comment]
I seen the bump earlier. You're doing awesome man
